apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: builds.registry.svc.cluster.local/ystack-examples/k8s-endpoints-sync-controller
    context: ../
    custom:
      buildCommand: ../y-stack/ystack-build.sh
      dependencies:
        dockerfile:
          path: ./Dockerfile
deploy:
  kustomize:
    path: .

